import { AvatarPart } from "../types/avatar";
import { PART_CONFIG } from "./partConfig";

const BASE_URL = "/test-parts";
const CX = 256; // canvas center X
const CY = 350; // face center Y

export const TEST_PARTS: AvatarPart[] = [
  {
    id: "hair_back",
    name: "後ろ髪",
    imageUrl: `${BASE_URL}/hair_back.png`,
    anchorX: 0.5, anchorY: 0.3,
    baseX: CX, baseY: CY - 40,
    baseWidth: 220, baseHeight: 280,
    ...PART_CONFIG.hair_back,
  },
  {
    id: "face",
    name: "顔",
    imageUrl: `${BASE_URL}/face.png`,
    anchorX: 0.5, anchorY: 0.4,
    baseX: CX, baseY: CY,
    baseWidth: 200, baseHeight: 250,
    ...PART_CONFIG.face,
  },
  {
    id: "left_white",
    name: "左白目",
    imageUrl: `${BASE_URL}/left_white.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX - 38, baseY: CY - 20,
    baseWidth: 40, baseHeight: 25,
    ...PART_CONFIG.left_white,
  },
  {
    id: "right_white",
    name: "右白目",
    imageUrl: `${BASE_URL}/right_white.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX + 38, baseY: CY - 20,
    baseWidth: 40, baseHeight: 25,
    ...PART_CONFIG.right_white,
  },
  {
    id: "left_pupil",
    name: "左瞳",
    imageUrl: `${BASE_URL}/left_pupil.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX - 38, baseY: CY - 20,
    baseWidth: 20, baseHeight: 20,
    ...PART_CONFIG.left_pupil,
  },
  {
    id: "right_pupil",
    name: "右瞳",
    imageUrl: `${BASE_URL}/right_pupil.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX + 38, baseY: CY - 20,
    baseWidth: 20, baseHeight: 20,
    ...PART_CONFIG.right_pupil,
  },
  {
    id: "left_upper_lid",
    name: "左上まぶた",
    imageUrl: `${BASE_URL}/left_upper_lid.png`,
    anchorX: 0.5, anchorY: 1.0,
    baseX: CX - 38, baseY: CY - 8,
    baseWidth: 45, baseHeight: 12,
    ...PART_CONFIG.left_upper_lid,
  },
  {
    id: "right_upper_lid",
    name: "右上まぶた",
    imageUrl: `${BASE_URL}/right_upper_lid.png`,
    anchorX: 0.5, anchorY: 1.0,
    baseX: CX + 38, baseY: CY - 8,
    baseWidth: 45, baseHeight: 12,
    ...PART_CONFIG.right_upper_lid,
  },
  {
    id: "left_brow",
    name: "左眉",
    imageUrl: `${BASE_URL}/left_brow.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX - 38, baseY: CY - 45,
    baseWidth: 50, baseHeight: 8,
    ...PART_CONFIG.left_brow,
  },
  {
    id: "right_brow",
    name: "右眉",
    imageUrl: `${BASE_URL}/right_brow.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX + 38, baseY: CY - 45,
    baseWidth: 50, baseHeight: 8,
    ...PART_CONFIG.right_brow,
  },
  {
    id: "nose",
    name: "鼻",
    imageUrl: `${BASE_URL}/nose.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX, baseY: CY + 20,
    baseWidth: 15, baseHeight: 12,
    ...PART_CONFIG.nose,
  },
  {
    id: "mouth",
    name: "口",
    imageUrl: `${BASE_URL}/mouth.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX, baseY: CY + 50,
    baseWidth: 40, baseHeight: 15,
    ...PART_CONFIG.mouth,
  },
  {
    id: "blush_left",
    name: "左頬染め",
    imageUrl: `${BASE_URL}/blush_left.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX - 55, baseY: CY + 15,
    baseWidth: 30, baseHeight: 20,
    ...PART_CONFIG.blush_left,
  },
  {
    id: "blush_right",
    name: "右頬染め",
    imageUrl: `${BASE_URL}/blush_right.png`,
    anchorX: 0.5, anchorY: 0.5,
    baseX: CX + 55, baseY: CY + 15,
    baseWidth: 30, baseHeight: 20,
    ...PART_CONFIG.blush_right,
  },
  {
    id: "hair_front",
    name: "前髪",
    imageUrl: `${BASE_URL}/hair_front.png`,
    anchorX: 0.5, anchorY: 0.8,
    baseX: CX, baseY: CY - 30,
    baseWidth: 180, baseHeight: 80,
    ...PART_CONFIG.hair_front,
  },
  {
    id: "hair_side_left",
    name: "左横髪",
    imageUrl: `${BASE_URL}/hair_side_left.png`,
    anchorX: 0.8, anchorY: 0.2,
    baseX: CX - 95, baseY: CY - 20,
    baseWidth: 40, baseHeight: 150,
    ...PART_CONFIG.hair_side_left,
  },
  {
    id: "hair_side_right",
    name: "右横髪",
    imageUrl: `${BASE_URL}/hair_side_right.png`,
    anchorX: 0.2, anchorY: 0.2,
    baseX: CX + 95, baseY: CY - 20,
    baseWidth: 40, baseHeight: 150,
    ...PART_CONFIG.hair_side_right,
  },
];
